server:
  port: 7999 #1

eureka:
  instance:
    hostname: eureka2  #2
  client:
    register-with-eureka: false  #3
    fetch-registry: false
    server-url:
      defaultZone: http://eureka1:7998/eureka
